version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    env_file: .env
    volumes:
      - ./:/home/space/app:Z
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
